services:
  neuron:
    profiles: ["miner", "miner-tee", "miner-tee-vpn", "validator", "validator-tee"]
    image: masaengineering/subnet-42:latest
    pull_policy: always
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
    deploy:
      resources:
        limits:
          memory: ${NEURON_MEMORY_LIMIT:-0}
          cpus: ${NEURON_CPU_LIMIT:-0}
        reservations:
          memory: ${NEURON_MEMORY_RESERVATION:-0}
          cpus: ${NEURON_CPU_RESERVATION:-0}
    ports:
      - "${VALIDATOR_PORT:-8090}:${VALIDATOR_PORT:-8090}"
      - "${MINER_PORT:-8091}:${MINER_PORT:-8091}"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"
  
  worker:
    profiles: ["tee", "miner-tee", "validator-tee"]
    image: masaengineering/tee-worker:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${TEE_PORT:-8080}:${TEE_PORT:-8080}"
    deploy:
      resources:
        limits:
          memory: ${WORKER_MEMORY_LIMIT:-0}
          cpus: ${WORKER_CPU_LIMIT:-0}
        reservations:
          memory: ${WORKER_MEMORY_RESERVATION:-0}
          cpus: ${WORKER_CPU_RESERVATION:-0}
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    network_mode: host
    volumes:
      - ./.env:/home/masa/.env
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"

  worker-vpn:
    profiles: ["miner-tee-vpn"]
    image: masaengineering/tee-worker:latest
    pull_policy: always
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${WORKER_MEMORY_LIMIT:-0}
          cpus: ${WORKER_CPU_LIMIT:-0}
        reservations:
          memory: ${WORKER_MEMORY_RESERVATION:-0}
          cpus: ${WORKER_CPU_RESERVATION:-0}
    ports:
      - "${TEE_PORT:-8080}:${TEE_PORT:-8080}"
    environment:
      - http_proxy=http://vpn:${VPN_PORT:-3128}
      - https_proxy=http://vpn:${VPN_PORT:-3128}
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - cookies-volume:/home/masa
      - ./.env:/home/masa/.env
    depends_on:
      vpn:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"

  vpn:
    profiles: ["vpn","miner-tee-vpn"]
    build:
      context: .
      dockerfile: Dockerfile.vpn
    image: vpn-service:latest
    pull_policy: never
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "${VPN_PORT:-3128}:${VPN_PORT:-3128}"
    volumes:
      - ./vpn:/etc/openvpn/config
    env_file: .env
    healthcheck:
      test: ["CMD", "bash", "-c", "[ \"$(cat /tmp/vpn_ready)\" = \"1\" ]"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"

  cookies-generator:
    profiles: ["cookies-refresh"]
    image: cookie-generator:latest
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile.cookies.generator
    volumes:
      - ./.env:/app/.env
      - ./cookies:/app/cookies
    environment:
      - PYTHONUNBUFFERED=1
      - ENABLE_VNC=true
      - RUNNING_IN_DOCKER=true
    restart: "no"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"

  cookies-updater:
    profiles: ["cookies-refresh"]
    image: cookies-updater:latest
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile.cookies.updater
    volumes:
      - ./.env:/app/.env
      - ${PWD}/cookies:/app/cookies
      - ./key.pem:/app/key.pem:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - COOKIES_REMOTE_HOSTS=${COOKIES_REMOTE_HOSTS:-localhost}
      - COOKIES_REMOTE_USER=${COOKIES_REMOTE_USER:-azureuser}
      - COOKIES_REMOTE_DIR=${COOKIES_REMOTE_DIR:-/tmp/cookies-upload}
      - PYTHONUNBUFFERED=1
    restart: "no"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"
    depends_on:
      cookies-generator:
        condition: service_completed_successfully

  watchtower:
    profiles: ["miner", "miner-tee", "miner-tee-vpn", "validator", "validator-tee"]
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 7200 --cleanup

volumes:
  cookies-volume:
