FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y openvpn curl iptables tinyproxy

# Configure system
RUN echo "net.ipv4.ip_forward=1" > /etc/sysctl.conf && \
    echo "Allow 0.0.0.0/0" >> /etc/tinyproxy/tinyproxy.conf

# Setup entrypoint script
COPY entrypoint-vpn.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"] 